spring:
  application:
    name: gateway-zuul-demo
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
