spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/unicodezh/config
          username: 13580103459
          password: zh123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
server:
  port: 9100
